/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menú;

/**
 *
 * @author HP
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        this.setTitle("Wictory 13");
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciarRompecabezas = new javax.swing.JButton();
        iniciarPerdidos = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarRompecabezas.setBackground(new java.awt.Color(153, 0, 153));
        iniciarRompecabezas.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        iniciarRompecabezas.setForeground(new java.awt.Color(255, 255, 255));
        iniciarRompecabezas.setText("Rompecabezas");
        iniciarRompecabezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarRompecabezasActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarRompecabezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 300, 50));

        iniciarPerdidos.setBackground(new java.awt.Color(153, 0, 153));
        iniciarPerdidos.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        iniciarPerdidos.setForeground(new java.awt.Color(255, 255, 255));
        iniciarPerdidos.setText("Perdidos en el espacio");
        iniciarPerdidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarPerdidosActionPerformed(evt);
            }
        });
        getContentPane().add(iniciarPerdidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 300, 50));

        regresar.setBackground(new java.awt.Color(255, 102, 0));
        regresar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        regresar.setForeground(new java.awt.Color(255, 255, 255));
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menú/Imagenes/menuJ.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarRompecabezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarRompecabezasActionPerformed
                
                this.setVisible(false);
                new menuR().setVisible(true);

    }//GEN-LAST:event_iniciarRompecabezasActionPerformed

    private void iniciarPerdidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarPerdidosActionPerformed
                this.setVisible(false);
                new Tutorial1().setVisible(true);
    }//GEN-LAST:event_iniciarPerdidosActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
            
        this.setVisible(false);
        new Menú().setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciarPerdidos;
    private javax.swing.JButton iniciarRompecabezas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
