/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menú;

import rompecabezasmercury13.RompecabezasMercury13;

/**
 *
 * @author HP
 */
public class menuR extends javax.swing.JFrame {

    public static int i = 1;
    
    public menuR() {
        this.setTitle("Wictory 13");
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nivelDificil = new javax.swing.JButton();
        nivelIntermedio = new javax.swing.JButton();
        nivelFacil = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selecciona la dificultad del rompecabezas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 510, -1));

        nivelDificil.setBackground(new java.awt.Color(153, 0, 153));
        nivelDificil.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        nivelDificil.setForeground(new java.awt.Color(255, 255, 255));
        nivelDificil.setText("Díficil");
        nivelDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelDificilActionPerformed(evt);
            }
        });
        getContentPane().add(nivelDificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 180, 50));

        nivelIntermedio.setBackground(new java.awt.Color(153, 0, 153));
        nivelIntermedio.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        nivelIntermedio.setForeground(new java.awt.Color(255, 255, 255));
        nivelIntermedio.setText("Intermedio");
        nivelIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelIntermedioActionPerformed(evt);
            }
        });
        getContentPane().add(nivelIntermedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 120, 50));

        nivelFacil.setBackground(new java.awt.Color(153, 0, 153));
        nivelFacil.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        nivelFacil.setForeground(new java.awt.Color(255, 255, 255));
        nivelFacil.setText("Fácil");
        nivelFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelFacilActionPerformed(evt);
            }
        });
        getContentPane().add(nivelFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 50));

        Regresar.setBackground(new java.awt.Color(255, 102, 0));
        Regresar.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        Regresar.setForeground(new java.awt.Color(255, 255, 255));
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menú/Imagenes/menu2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivelDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelDificilActionPerformed
        i = 3;
        new RompecabezasMercury13();
    }//GEN-LAST:event_nivelDificilActionPerformed

    private void nivelFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelFacilActionPerformed
        i = 1;
        new RompecabezasMercury13();
    }//GEN-LAST:event_nivelFacilActionPerformed

    private void nivelIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelIntermedioActionPerformed
        i = 2;
        new RompecabezasMercury13();
    }//GEN-LAST:event_nivelIntermedioActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
            this.setVisible(false);
            new Menu2().setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nivelDificil;
    private javax.swing.JButton nivelFacil;
    private javax.swing.JButton nivelIntermedio;
    // End of variables declaration//GEN-END:variables
}
