/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menú;

/**
 *
 * @author HP
 */
public class Tutorial1 extends javax.swing.JFrame {

    /**
     * Creates new form Tutorial1
     */
    public Tutorial1() {
        this.setTitle("Perdidos en el espacio");
        this.setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sgte = new javax.swing.JButton();
        rgr = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sgte.setBackground(new java.awt.Color(102, 0, 102));
        sgte.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        sgte.setForeground(new java.awt.Color(255, 255, 255));
        sgte.setText("Siguiente");
        sgte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgteActionPerformed(evt);
            }
        });
        getContentPane().add(sgte, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, -1, -1));

        rgr.setBackground(new java.awt.Color(102, 0, 102));
        rgr.setFont(new java.awt.Font("Bahnschrift", 1, 11)); // NOI18N
        rgr.setForeground(new java.awt.Color(255, 255, 255));
        rgr.setText("Regresar");
        rgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgrActionPerformed(evt);
            }
        });
        getContentPane().add(rgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menú/Imagenes/Tutorial1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sgteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgteActionPerformed
        this.setVisible(false);
        new Tutorial2().setVisible(true);
    }//GEN-LAST:event_sgteActionPerformed

    private void rgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgrActionPerformed
        this.setVisible(false);
        new Menu2().setVisible(true);
    }//GEN-LAST:event_rgrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tutorial1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton rgr;
    private javax.swing.JButton sgte;
    // End of variables declaration//GEN-END:variables
}
